apiVersion: v1
kind: Pod
metadata:
  name: config-pod-direct
spec:
  containers:
  - name: config-pod-direct
    image: nginx
    envFrom:
    - configMapRef: # u will get everything full acess under this config map now as env variables.
        name: course-config